name: CI

on:
  push:
    branches: [main]
  pull_request_target:
    branches: [main]

jobs:
  fmt-check:
    name: make fmt-check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - run: npm install --save-dev
      - run: make fmt-check

  lint-check:
    name: make lint-check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - run: npm install --save-dev
      - run: make lint-check

  tests:
    name: make test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Huff
        uses: cakevm/huff-neo-toolchain@v1
        with:
          version: latest

      - name: Run Tests
        run: make test
